name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          docker-compose build
          docker-compose run --rm app sh -c "pip install -r /tmp/requirements.txt"

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Linting
        run: docker-compose run --rm app sh -c "flake8"
