---
# Github action yml file for github
name: Checks

on: [push] # trigger a push

jobs:
  test-lint: # new test of the job id - text-lint
    name: Test and Lint
    runs-on: ubuntu-20.04 # runner that running our job on with ubuntu-20.04.
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # action that provide by github by default checkout docker jobs.
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test" # unit test our project
      - name: Linting
        run: docker-compose run --rm app sh -c "flake8" # lint our project
      # - name: Build
      #   run: docker-compose build # build our project
      # - name: Push
      #   run: docker-compose push # push our project to docker hub